version: "3.9"

services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: middleware
    networks:
      - mid
    depends_on:
      - cacheDB
      - jaeger
    ports:
      - 8000:8000 # REST port
      - 40001:40000 # Debug port
    volumes:
      - ./config.yml:/root/config.yml

  cacheDB:
    image: eqalpha/keydb
    restart: always
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: middleware-cacheDB
    networks:
      - mid
    volumes:
      - cacheData:/data
      - ./keyDB.conf:/etc/keydb/keydb.conf

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: middleware-jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
    volumes:
      - jagertmp:/tmp
    networks:
      - mid
  
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - mid
    volumes:
      - esdata:/usr/share/elasticsearch/data

  mongo:
    image: mongo:4.2
    restart: always
    networks:
      - mid
    volumes:
      - mongodata:/data/db
      - mongoconfigdb:/data/configdb

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.2
    environment:
      - GRAYLOG_ROOT_USERNAME=admin
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper  # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhosst:9000/ #Change me to real name host
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - mid
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - graylogdata:/usr/share/graylog/data
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      # - 1514:1514
      # Syslog UDP
      # - 1514:1514/udp
      # GELF TCP
      # - 12201:12201
      # GELF UDP
      # - 12201:12201/udp
    restart: always

volumes:
  cacheData:
    driver: local
  esdata:
    driver: local
  mongodata:
    driver: local
  mongoconfigdb:
    driver: local
  graylogdata:
    driver: local
  jagertmp:
    driver: local


networks:
  mid:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24